workflows:
  android-build:
    name: My Weather App
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: 20 # ВАЖНО: Обновляем до Node 20 для совместимости с RN 0.81
    scripts:
      - name: Install dependencies and prebuild
        script: |
          npm install
          npx expo install expo-location @react-native-community/netinfo
          
          rm -rf android
          npx expo prebuild --platform android --clean
          
          git checkout HEAD -- android/app/src/main/res/values/colors.xml || true

      - name: Build Android Release APK
        script: |
          cd android
          chmod +x gradlew
          
          # В режиме Release Metro автоматически создаст бандл и упакует его в APK.
          # Нам не нужны никакие ручные команды или флаги -x.
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
