// Expo config plugin: per-ABI release APKs instead of one universal APK.
//
// Why a plugin and not a direct build.gradle edit: android/ is gitignored
// and regenerated by `expo prebuild --clean` on every CI run, so any manual
// edit would be wiped. This injects the `splits { abi { ... } }` block into
// android/app/build.gradle at prebuild time.
//
// Result of `assembleRelease`:
//   app-arm64-v8a-release.apk  (modern devices, ~60MB)
//   app-armeabi-v7a-release.apk (old 32-bit devices, ~55MB)
// No universal APK (universalApk false) — each file carries native .so libs
// for exactly one architecture, ~35-40% smaller than the ~94MB universal
// build. The GitHub Actions workflow uploads both files to the release.
const { withAppBuildGradle } = require('@expo/config-plugins');

const SPLITS_BLOCK = `splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a', 'armeabi-v7a'
            universalApk false
        }
    }`;

module.exports = function withAbiSplits(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      return config;
    }
    const contents = config.modResults.contents;
    if (contents.includes('universalApk false')) {
      return config; // already applied (idempotent)
    }
    config.modResults.contents = contents.replace(
      /android\s*\{/,
      `android {\n    ${SPLITS_BLOCK}`
    );
    return config;
  });
};
